# Generated by Django 5.2.17 on 2026-09-25 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="IT's short name for the account, like the heading in the old spreadsheet.", max_length=60, unique=True, verbose_name='name')),
                ('email', models.EmailField(help_text='The email address this Zoom account signs in with.', max_length=254, unique=True, verbose_name='Zoom sign-in email')),
                ('is_paid', models.BooleanField(default=True, help_text='Untick for free accounts. Free accounts end meetings after 40 minutes, so they are never booked.', verbose_name='paid account')),
                ('is_active', models.BooleanField(default=True, help_text="Untick to stop booking this account. Accounts with bookings can't be deleted, only taken out of use.", verbose_name='in use')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers are suggested first when several accounts are free.', verbose_name='order')),
                ('credential_set', models.SlugField(blank=True, help_text="Name of this account's Zoom API credentials in the server settings, like zoom-01. Leave empty until the live Zoom connection is set up.", max_length=40, verbose_name='credential set')),
                ('host_key_encrypted', models.TextField(blank=True, editable=False, help_text='The host key, encrypted. Set it with the Host key field in the admin.', verbose_name='host key (encrypted)')),
                ('notes', models.TextField(blank=True, help_text='Anything IT should remember.', verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Zoom host account',
                'verbose_name_plural': 'Zoom host accounts',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='The name students and IT will see, like CCC Batch 3 - Mathematics.', max_length=200, verbose_name='class name')),
                ('notes', models.TextField(blank=True, help_text='Anything IT should know.', max_length=1000, verbose_name='notes for IT')),
                ('wants_recording', models.BooleanField(default=False, help_text='The requester asked for the class to be recorded to the Zoom cloud.', verbose_name='recording asked for')),
                ('first_date', models.DateField(help_text='For a weekly class, the date of the first class.', verbose_name='date of the class')),
                ('start_time', models.TimeField(help_text='Sri Lanka time, on a 5-minute step.', verbose_name='starts at')),
                ('end_time', models.TimeField(help_text='On the same day as it starts.', verbose_name='ends at')),
                ('repeat', models.CharField(choices=[('once', 'Just once'), ('weekly', 'Every week')], default='once', max_length=10, verbose_name='how often')),
                ('weekdays', models.CharField(blank=True, help_text='For weekly classes: ISO day numbers, 1 is Monday, like 1,3.', max_length=13, verbose_name='days of the week')),
                ('last_date', models.DateField(blank=True, help_text='For weekly classes: every ticked day is booked up to and including it.', null=True, verbose_name='date of the last class')),
                ('requester_name', models.CharField(max_length=150, verbose_name="requester's name")),
                ('requester_email', models.EmailField(help_text='Confirmed by the requester before IT sees the request.', max_length=254, verbose_name="requester's email")),
                ('requester_phone', models.CharField(help_text='Stored in international form.', max_length=16, verbose_name="requester's phone")),
                ('submitted_ip', models.GenericIPAddressField(blank=True, help_text='Used only to limit how many requests one address can send in an hour.', null=True, verbose_name='sent from IP address')),
                ('status', models.CharField(choices=[('unverified', 'Waiting for email check'), ('waiting', 'Waiting for IT'), ('approved', 'Link sent'), ('rejected', 'Not approved')], db_index=True, default='unverified', max_length=12, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email confirmed')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided')),
                ('rejection_reason', models.TextField(blank=True, help_text='Emailed to the requester.', verbose_name='reason for not approving')),
                ('meeting_id', models.CharField(blank=True, max_length=32, verbose_name='meeting ID')),
                ('join_url', models.URLField(blank=True, max_length=1000, verbose_name='Zoom link')),
                ('passcode', models.CharField(blank=True, max_length=10, verbose_name='passcode')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('host_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='link_requests', to='zoom.hostaccount', verbose_name='booked on')),
            ],
            options={
                'verbose_name': 'Zoom link request',
                'verbose_name_plural': 'Zoom link requests',
                'ordering': ['-created_at'],
                'permissions': [('review_linkrequest', 'Can approve or reject Zoom link requests')],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='starts')),
                ('ends_at', models.DateTimeField(verbose_name='ends')),
                ('host_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='zoom.hostaccount', verbose_name='booked on')),
                ('link_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='zoom.linkrequest', verbose_name='request')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['starts_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HostSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='slot starts')),
                ('host_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='zoom.hostaccount', verbose_name='account')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='zoom.occurrence', verbose_name='class')),
            ],
            options={
                'verbose_name': 'booked slot',
                'verbose_name_plural': 'booked slots',
                'ordering': ['host_account', 'starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='linkrequest',
            index=models.Index(fields=['requester_email', 'created_at'], name='zoom_lr_email_created'),
        ),
        migrations.AddIndex(
            model_name='linkrequest',
            index=models.Index(fields=['submitted_ip', 'created_at'], name='zoom_lr_ip_created'),
        ),
        migrations.AddConstraint(
            model_name='linkrequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='zoom_linkrequest_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='linkrequest',
            constraint=models.CheckConstraint(condition=models.Q(('repeat', 'once'), models.Q(('last_date__isnull', False), models.Q(('weekdays', ''), _negated=True)), _connector='OR'), name='zoom_linkrequest_weekly_has_days_and_end'),
        ),
        migrations.AddConstraint(
            model_name='linkrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), models.Q(('host_account__isnull', False), models.Q(('join_url', ''), _negated=True)), _connector='OR'), name='zoom_linkrequest_approved_has_link'),
        ),
        migrations.AddConstraint(
            model_name='linkrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='zoom_linkrequest_rejected_has_reason'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['host_account', 'starts_at'], name='zoom_occ_host_start'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='zoom_occurrence_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='hostslot',
            constraint=models.UniqueConstraint(fields=('host_account', 'starts_at'), name='zoom_one_booking_per_account_slot'),
        ),
    ]
