# Generated by Django 5.2.17 on 2026-09-25 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_it_desk_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostaccount',
            name='host_key_changed_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When a host key was last saved or removed. Empty for keys saved before this was recorded.', null=True, verbose_name='host key last changed'),
        ),
        migrations.AddField(
            model_name='hostaccount',
            name='host_key_changed_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Who last saved or removed the host key.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='host key last changed by'),
        ),
        migrations.AlterField(
            model_name='hostaccount',
            name='host_key_encrypted',
            field=models.TextField(blank=True, editable=False, help_text='Set it on the Zoom accounts page.', verbose_name='host key (encrypted)'),
        ),
    ]
