# Generated by Django 5.2.17 on 2026-09-25 09:55
"""The live Zoom connection (brief 006, criterion 41).

- ``Occurrence.zoom_occurrence_id``: Zoom's ID for each class of a weekly meeting, so brief
  011 can cancel a single class. Blank for existing rows, which is correct: they were made by
  the manual or fake provider.
- ``HostAccount.credential_set``: now "Zoom connection name", with the name rule as a
  validator and new help. Schema-wise only the metadata changes; no value is rewritten.
- ``HostAccount.label``: the help text no longer mentions the old spreadsheet (D18).

Schema only, no data: reversing it drops the new column and restores the old help texts.
"""

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_it_desk_manages_host_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='zoom_occurrence_id',
            field=models.CharField(blank=True, help_text="Zoom's ID for this class within its weekly meeting, when Zoom made it.", max_length=20, verbose_name='Zoom occurrence ID'),
        ),
        migrations.AlterField(
            model_name='hostaccount',
            name='credential_set',
            field=models.SlugField(blank=True, help_text="The name of this account's Zoom connection on the server, like zoom-01. Whoever looks after the server tells you the name.", max_length=40, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(-[a-z0-9]+)*\\Z', code='invalid', message='Use lower-case letters, numbers and hyphens only, like zoom-01.')], verbose_name='Zoom connection name'),
        ),
        migrations.AlterField(
            model_name='hostaccount',
            name='label',
            field=models.CharField(help_text="IT's short name for the account, like Zoom 01.", max_length=60, unique=True, verbose_name='name'),
        ),
    ]
