# Generated by Django 5.2.17 on 2026-09-26 07:00
"""Cancelling a booking, and the host-key reveal record (brief 011, criteria 1 and 40).

- ``LinkRequest``: the ``cancelled`` status, ``cancelled_at`` / ``cancelled_by``, and the check
  that a cancelled request had a link and says when.
- ``Occurrence``: ``cancelled_at`` / ``cancelled_by`` / ``cancel_reason``, and the check that a
  cancelled class says why.
- ``HostKeyReveal``: who was shown an account's host key, and when. No key is stored.
- The review permission's new name in ``Meta`` (state only; ``0007`` renames the stored row).

Schema only: every new column is nullable or blank, so existing rows need no values, and
reversing it drops them again.

Reversing it after real cancels loses the cancel data: who cancelled, when and why are
dropped with their columns and can't be recovered, and the requests stay in the
``cancelled`` status, which the reversed code doesn't know. A cancelled class on a booking
that's still approved would also look booked again, though its slots are gone. Back up the
database before reversing it on a live system (review round 1 nit).
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0005_zoom_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostKeyReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField(auto_now_add=True, verbose_name='shown')),
            ],
            options={
                'verbose_name': 'host key reveal',
                'verbose_name_plural': 'host key reveals',
                'ordering': ['-shown_at', '-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='linkrequest',
            options={'ordering': ['-created_at'], 'permissions': [('review_linkrequest', 'Can approve, reject, reschedule or cancel Zoom link requests')], 'verbose_name': 'Zoom link request', 'verbose_name_plural': 'Zoom link requests'},
        ),
        migrations.AddField(
            model_name='linkrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the IT desk cancelled the booking.', null=True, verbose_name='cancelled'),
        ),
        migrations.AddField(
            model_name='linkrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Who in the IT desk cancelled the booking.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text="Why the class was cancelled. It's emailed to the requester.", verbose_name='reason for cancelling'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the IT desk cancelled this class.', null=True, verbose_name='cancelled'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Who in the IT desk cancelled this class.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by'),
        ),
        migrations.AlterField(
            model_name='linkrequest',
            name='status',
            field=models.CharField(choices=[('unverified', 'Waiting for email check'), ('waiting', 'Waiting for IT'), ('approved', 'Link sent'), ('rejected', 'Not approved'), ('cancelled', 'Cancelled')], db_index=True, default='unverified', max_length=12, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='linkrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('host_account__isnull', False), models.Q(('join_url', ''), _negated=True), ('cancelled_at__isnull', False)), _connector='OR'), name='zoom_linkrequest_cancelled_was_booked'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_at__isnull', True), models.Q(('cancel_reason', ''), _negated=True), _connector='OR'), name='zoom_occurrence_cancel_has_reason'),
        ),
        migrations.AddField(
            model_name='hostkeyreveal',
            name='host_account',
            field=models.ForeignKey(help_text='The Zoom account whose host key was shown.', on_delete=django.db.models.deletion.PROTECT, related_name='key_reveals', to='zoom.hostaccount', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='hostkeyreveal',
            name='shown_by',
            field=models.ForeignKey(help_text='The IT desk member who pressed Show host key.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='shown to'),
        ),
    ]
